### PR TITLE
feat(template): Recreate Notion's magic link email

### PR DESCRIPTION
**Pull request by guscsales**
### Description

The Notion magic link template raised on this issue: https://github.com/zenorocha/react-email/issues/122

### Screenshots

image
IMG_2429E3A68E33-1

### CODE REVIEW

**Comment by zenorocha** [comment]
After testing with litmus, here's what I found:

**Outlook 2021 (Win 10)**

image

**iPhone 12 (iOS 14.2)** 

image

**Comment by guscsales** [comment]
just did some updates, @zenorocha I don't have an account on Litmus, so could you test again on Outlook, please?

**Comment by bukinoshita** [comment]
We definitely need to improve the way we test these templates.

But sharing here the screenshots.
screenshot 2022-09-28 at 15 44 45@2x
screenshot 2022-09-28 at 15 44 32@2x

**Comment by bukinoshita** [comment]
Here's some comments

screenshot 2022-09-28 at 15 46 28@2x
screenshot 2022-09-28 at 15 46 34@2x
screenshot 2022-09-28 at 15 47 08@2x


screenshot 2022-09-28 at 15 47 13@2x

**Comment by guscsales** [comment]
I've dropped another commit, hope Outlook fixes on that push.

Related to accessibility: fixed all.

Related to the links: I've updated both for "https://notion.so" with target blank, since this is an example email I don't think we will have real links.

Related to the image blocker: maybe we can upload the notion logo in some bucket of React Email. I'm using the logo from Notion's website, following the same pattern of Vercel's template, which is using Vercel's static files. What you think?

**Pull request merged**
