### PR TITLE
feat(column): Add `Column` component

### PR DESCRIPTION
**Pull request by cassiorsfreitas**
This PR closes https://github.com/zenorocha/react-email/issues/160 and adds Section component according to the [mjml](https://documentation.mjml.io/) reference and the components already created in this repository.

```
const Email = () => {
  return (
    <Html lang="en">
      <Body style={{ backgroundColor: '#61dafb' }}>
        <Section>
          <Column style={{ width: '50%'}}>
              {/* First column */}
          </Column>
          <Column style={{ width: '50%'}}>
              {/* Second column */}
          </Column>
        </Section>
      </Body>
    </Html>
  );
};
```

### CODE REVIEW

**Comment by cassiorsfreitas** [comment]
Quick question. What is the componentization structure that the library intends to follow?

Flowchart react-email suggestion

**Comment by bukinoshita** [comment]
Can you check the CI errors?

**Comment by cassiorsfreitas** [comment]
@bukinoshita the CI error of this PR and https://github.com/zenorocha/react-email/pull/164 happens because of the build of another component:

Screenshot 2022-11-01 at 13 24 23

Can I change it or is this already being fixed?

**Comment by bukinoshita** [comment]
Can you double check? I fixed the previous error, need to format the code.

**Comment by cassiorsfreitas** [comment]
@bukinoshita done

**Pull request merged**
